name: Backend CI

on:
  push:
    branches: [ "develop", "main" ]
    paths:
      - 'Backend/**'
      - 'client/**'
  pull_request:
    branches: [ "develop" ]
    paths:
      - 'Backend/**'

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x 

    - name: Restore dependencies
      # Robot sẽ vào folder Backend để tìm file .sln hoặc .csproj
      run: dotnet restore ./Backend/*.csproj 

    - name: Build
      run: dotnet build ./Backend/*.csproj --no-restore