name: Backend CI

on:
  push:
    branches: [ "develop", "main" ]
    paths:
      - 'Backend/**' # Chỉ chạy khi có thay đổi trong folder Backend
  pull_request:
    branches: [ "develop" ]
    paths:
      - 'Backend/**'

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x # Đảm bảo đúng version .NET bạn đang dùng

    - name: Restore dependencies
      run: dotnet restore ./Backend/*.sln # Tự động tìm file solution trong folder Backend

    - name: Build
      run: dotnet build ./Backend/*.sln --no-restore